title:              Судэксперт
baseURL:            /
publishDir:         public/msk

params:
  city:             Москва
  subtitle:         Все виды экспертиз
  description:      Судебная экспертиза и инициативные исследования любого уровня сложности. Рецензирование заключений экспертов.
  authors:          Степан Горшенин, Сергей Кежаев, и другие...
  contact:
    phone:          '+7 (903) 137-56-58'
    email:          Ex.63@yandex.ru
  social:
    telegram:       '+79276195082'
    whatsapp:       '+79276195082'
  map:
    latitude:       55.774369
    longitude:      37.602987

build:
  _merge: deep