title: Судэксперт
baseURL: /
languageCode: ru
publishDir: public/dev
enableRobotsTXT: true
disableKinds: ["404", "RSS"]
metaDataFormat: yaml

params:
  lang: ru
  city: Тольятти
  subtitle: Все виды экспертиз
  description: Судебная экспертиза и инициативные исследования любого уровня сложности. Рецензирование заключений экспертов.
  authors: Степан Горшенин, Сергей Кежаев, и другие...
  contact:
    phone: +7 (8482) 63-12-88
    email: sud163@ya.ru
    postalCode: 445047
    adress: ул.Тополиная 1-Б, оф.214
  social:
    telegram: "+79278993666"
    whatsapp: "+79278993666"
  map:
    latitude: 53.544781
    longitude: 49.347234
  container: container

  current_version: 1.0.1
  github_org: https://github.com/oooSudexpert/HugoSite

taxonomies:
  service: services
  tag: tags

permalinks:
  page:
    posts: /articles/:year/:month/:slug/
    services: /services/:slug/
  section:
    posts: /articles/
  services: /services/:slug/

menus:
  main:
    - name: Главная
      pageRef: /
      weight: 10
    - name: Экспертиза
      pageRef: /services
      weight: 20
    - name: Статьи
      pageRef: /posts
      weight: 30
    - name: Контакты
      pageRef: /contact
      weight: 40

module:
  mounts:
    - source: assets
      target: assets
    - source: static
      target: assets
