name: Deploy sudexpert.ooo website to Yandex Object Storage
on:
    push:
        branches:
            - master            
jobs:
    deploy:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [16.x]
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
    
            - name: Install NPM dependencies
              run: npm ci
    
            - name: Build application
              run: npm run build
    
            - uses: sergeevpasha/yandex-cloud-s3-sync-github-actions@v0.1.0
              with:
                YANDEX_CLOUD_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
                YANDEX_CLOUD_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
                YANDEX_CLOUD_BUCKET_NAME: ${{ secrets.BUCKET }}
                YANDEX_CLOUD_REGION: ru-central1-a
                PATH: "./public/tlt"
                CLEAR: true
